# Numpy

#### Documentation:

In [24]:
#For full documentation
website = "https://numpy.org/"
import webbrowser
webbrowser.open(website)

True

## Creatinng Arrays

1. Import the numpy library and check its version.

In [1]:
import numpy as np

In [3]:
np.__version__


'1.16.2'

## Arrays from lists
### 1-D Array 

2. Given the following **list1** create a numpy array and print it.
* Check the type of the array
* Check the type of the elements inside the array

In [15]:
list1 = [15,20,35,30,35]

In [6]:
np.array(list1)

array([15, 20, 35, 30, 35])

5. Use **list1** and create an array of float elements, than check the type.

In [10]:
x=np.array(list1, dtype='float')
type(x)

numpy.ndarray

### 2-D array using lists

6. Combine **list1** and **list2** and create a 2-D array. 

In [13]:
list2 = [10,20,30,40]

In [21]:
l3=[list1,list2]
l3=np.array(l3)
l3

array([list([15, 20, 35, 30, 35]), list([10, 20, 30, 40])], dtype=object)

7. Check the shape of your 2-D array.

In [22]:
l3.shape

(2,)

## The .arange() method

#### 1-D array

8. Use the **arange** method and create a 1-D array of 15 elements.  

In [23]:
array_1d = np.arange(15)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

9. Use the **arange** method and create a 1-D array, start=20, stop=60, steps=2

In [25]:
array_1d = np.arange(20,60,2)
array_1d

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

#### 2-D array, the reshape method

10. Use the **arange** and **reshape** methods. Create an array of 20 elements and shape it 5x4. 

In [27]:
array_2d = np.arange(0, 20).reshape(5,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### 3-D array

11. Use the **arange** and **reshape** methods. Create an array of 40 elements and shape it 2x5x4.

In [29]:
x=np.arange(40).reshape(2,5,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

## Linespace method

12. Use the **linespace** method and create a 1-D array from 0 to 1 with 10 elements inside.

In [32]:
y=np.linspace(0,1,10)
y

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## The randoms methods

13. Use the **random.rand** method and create an array of 15 elements random sampled from a uniform distribution over [0, 1).



In [34]:
t=np.random.rand(15)
t

array([0.85360849, 0.53560855, 0.49212284, 0.35202173, 0.88908894,
       0.42724691, 0.25899343, 0.32317466, 0.67988981, 0.70685095,
       0.04517319, 0.57179507, 0.11290561, 0.09528558, 0.1041659 ])

#### random.randn()

14. Create a 1-D array with 20 elements sampled from the “standard normal” distribution.

In [36]:
r=np.random.randn(20)
r

array([-0.69552318,  0.25086156,  0.53978482,  0.97168629, -1.75308096,
       -0.94297472,  1.51507123,  0.44272655, -0.17264087,  1.13314879,
       -0.06715808,  0.72673374, -0.66901248,  0.83039514, -0.60287425,
        0.59868092,  0.46656645,  0.11199656, -0.81696324, -0.59000275])

### Special cases arrays

15. Create a 2-D array of zeros 4x4.

In [38]:
h=np.zeros((4,4))
h

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

16. Createe a 2-D array of ones 3x3.

In [43]:
h=np.ones((3,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

17. Use the **eye** method and create an array 4x4

In [44]:
h=np.eye(4)
h

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Congratulation! You completed all the exercises!