# Numpy

## Universal Array Functions

1. Import the numpy library

In [1]:
import numpy as np


2. Create a 1-D array with range from 1 to 15 and assign it to the vaeiable **"a"**

In [5]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

3. Compute the square root of every element of **a**

In [7]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

4. Compute the exponential (e^) for every element of **a**

In [8]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

5. Compute the Log10 for every element of **a**

In [9]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126])

### Binary Functions 

In the following exercises use universal functions (methods).

In [10]:
#Random array (normal dist)
A = np.random.randn(5)
A

array([ 0.45701752,  0.4731402 , -1.00213884,  0.45719954, -2.84852617])

In [11]:
#Random array (normal dist)
B = np.random.randn(5)
B

array([-0.8815955 ,  0.05035914, -0.13717601,  0.29416076,  1.10691626])

#### Addition

6. Add A and B two arrays

In [12]:
np.add(A,B)

array([-0.42457798,  0.52349934, -1.13931486,  0.75136031, -1.74160991])

#### Division

7. divide A with B

In [13]:
np.divide(A,B)

array([-0.5183982 ,  9.39532012,  7.30549614,  1.55425062, -2.57338904])

#### Maximun value

8. Find the maximum value between A and B element by element.  

In [14]:
np.minimum(A,B)

array([-0.8815955 ,  0.05035914, -1.00213884,  0.29416076, -2.84852617])

#### Minimum value

9. Find the minimum value between A and B element by element.

In [15]:
np.maximum(A,B)

array([ 0.45701752,  0.4731402 , -0.13717601,  0.45719954,  1.10691626])

#### Sort

10. Sort the array A

In [16]:
np.sort(A)

array([-2.84852617, -1.00213884,  0.45701752,  0.45719954,  0.4731402 ])

#### Unique Elements
11. Use the array below and print out the unique elements

In [18]:
animals = np.array(['dog', 'dog', 'cat','zebra','cat','cow','cow','cow'])


In [19]:
np.unique(animals)

array(['cat', 'cow', 'dog', 'zebra'], dtype='<U5')

#### if in

12. Find if the "cat" and "zebra" are inside the animals array

In [24]:
np.in1d(['cat','zebra', 'mammut'],animals)

array([ True,  True, False])

# Task completed! Congratulation!